version: 0.2

phases:
  install:
    commands:
      - pip install pytest

  build:
    commands:
      - echo Running tests...
      - python -m unittest discover   # This will FAIL

artifacts:
  files:
    - '**/*'
